redis:
    image: redis:alpine
    container_name: redis
    hostname: redis.rancher
    environment:
        RANCHER_SERVICE_NAME: redis
    labels:
        io.rancher.container.dns: true
        io.rancher.container.network : true
        io.rancher.container.hostname_override: container_name
        io.rancher.scheduler.affinity:host_label: net.dst=true
        io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    volumes:
      - /data/containers/mnt/redis/var/lib/redis:/var/lib/redis

psl:
  image: powerdata/modbus-worker:0.3
  command: "-q modbus --redis=redis.redis"
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network : true
    io.rancher.scheduler.affinity:host_label: net.dst=true
lawrencium:
  image: powerdata/modbus-worker:0.3
  command: "-q lawrencium --redis=redis.redis"
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network : true
    io.rancher.scheduler.affinity:host_label: net.lawrencium=true
master:
  image: powerdata/modbus-worker:0.3
  container_name: modbus_master
  entrypoint: python
  command: "./pulsar/scripts/pulsar_job_producer.py --redis=redis.redis --rabbit=rabbit.rabbitmq"
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network : true
    io.rancher.scheduler.affinity:host_label: net.dst=true
