FROM haproxy:1.5
COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
COPY portal.pem /etc/ssl/cyberpower/portal.pem
COPY rancher.pem /etc/ssl/cyberpower/rancher.pem
COPY dash.pem /etc/ssl/cyberpower/dash.pem
COPY grafana.pem /etc/ssl/cyberpower/grafana.pem
