redis:
    image: redis:alpine
    container_name: redis
    environment:
        RANCHER_SERVICE_NAME: redis
    labels:
        io.rancher.container.dns: true
        io.rancher.container.network : true
        io.rancher.container.hostname_override: container_name
        io.rancher.scheduler.affinity:host_label: net.dst=true
        io.rancher.scheduler.affinity:host_label: memory.large=true
        io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    entrypoint:
      - /usr/local/bin/docker-entrypoint.sh
      - redis-server
      - /var/lib/redis.conf
    volumes:
      - /data/containers/mnt/redis/data:/data
      - /data/containers/mnt/redis/conf:/var/lib

psl:
  image: powerdata/modbus-worker:0.14
  command: "-q dst --redis=redis"
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network : true
    io.rancher.scheduler.affinity:host_label: net.dst=true
  depends_on:
    - redis
  links:
   - redis
lawrencium:
  image: powerdata/modbus-worker:0.14
  command: "-q lawrencium --redis=redis"
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network : true
    io.rancher.scheduler.affinity:host_label: net.lawrencium=true
  depends_on:
    - redis
  links:
   - redis
  external_links:
   - rabbit.rabbitmq:rabbit
master:
  image: powerdata/modbus-worker:0.14
  container_name: modbus_master
  entrypoint: python
  command: "./pulsar/scripts/pulsar_job_producer.py --redis=redis --rabbit=rabbit"
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network : true
    io.rancher.scheduler.affinity:host_label: net.dst=true
  depends_on:
    - redis
  links:
   - redis
  external_links:
   - rabbit.rabbitmq:rabbit
