cassandra:
  container_name: cassandra
  image: 10.42.141.112:5000/lbnl/cassandra:0.2
  environment:
    RANCHER_ENABLE: 'true'
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.dns: true
    io.rancher.scheduler.affinity:host_label: net.dst=true
    io.rancher.container.network : true
  tty: true
  stdin_open: true
  volumes:
    - /data/cassandra


