cassandra:
  container_name: cassandra
  image: cassandra:3.7
  environment:
    RANCHER_ENABLE: 'true'
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.dns: true
    io.rancher.scheduler.affinity:host_label: net.dst=true
    io.rancher.container.network : true
  tty: true
  stdin_open: true
  volumes:
    - /data/containers/mnt/cassandra2:/var/lib/cassandra
