cassandra:
  container_name: cassandra
  image: pboos/rancher-cassandra:3.1
  environment:
    RANCHER_ENABLE: 'true'
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.dns: true
    io.rancher.scheduler.affinity:host_label: net.dst=true
    io.rancher.container.network : true
  tty: true
  stdin_open: true
  volumes:
    - /var/lib/cassandra


